# Generated by Django 4.2.1 on 2023-06-09 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_remove_order_note_order_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='fristemail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.EmailField(max_length=100)),
            ],
        ),
    ]
